---

# install confd package from repo
- name: confd | download and copy "confd" binary file to /usr/local/bin/
  get_url:
    url: '{{ item }}'
    dest: /usr/local/bin/confd
    mode: u+x,g+x,o+x
    timeout: 60
    validate_certs: no
  loop:
    - '{{ confd_package_repo }}'
  environment: '{{ proxy_env | default({}) }}'
  when: installation_method == "repo" and confd_package_repo | length > 0
  tags: [ get_confd, confd ]

# install confd package from file
- name: confd | copy "confd" binary file to /usr/local/bin/
  copy:
    src: '{{ confd_package_file }}'
    dest: /usr/local/bin/confd
    mode: u+x,g+x,o+x
  when: installation_method == "file" and confd_package_file | length > 0
  tags: [ get_confd, confd ]

- name: confd | create conf directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - /etc/confd/conf.d
    - /etc/confd/templates
  tags: [ confd_dir, confd_conf, confd ]

- block:
    - name: confd | generate conf file "/etc/confd/confd.toml"
      template:
        src: templates/confd.toml.j2
        dest: /etc/confd/confd.toml
      tags: confd_toml

    - name: confd | generate conf file "/etc/confd/conf.d/haproxy.toml"
      template:
        src: templates/haproxy.toml.j2
        dest: /etc/confd/conf.d/haproxy.toml
      tags: haproxy_toml

    - name: confd | generate template "/etc/confd/templates/haproxy.tmpl"
      template:
        src: templates/haproxy.tmpl.j2
        dest: /etc/confd/templates/haproxy.tmpl
      tags: haproxy_tmpl
  when: add_balancer is not defined or not add_balancer|bool
  tags: [ confd_conf, confd ]

- block: # for add_balancer.yml
    - name: confd | fetch confd.toml, haproxy.toml, haproxy.tmpl conf files from master
      run_once: true
      fetch:
        src: '{{ item }}'
        dest: files/
        validate_checksum: yes
        flat: yes
      loop:
       - /etc/confd/confd.toml
       - /etc/confd/conf.d/haproxy.toml
       - /etc/confd/templates/haproxy.tmpl
      delegate_to: '{{ groups.master[0] }}'

    - name: confd | copy confd.toml, haproxy.toml, haproxy.tmpl conf files to replica
      copy:
        src: 'files/{{ item.conf }}'
        dest: '{{ item.dest }}'
      loop:
       - { conf: 'confd.toml', dest: '/etc/confd/confd.toml'}
       - { conf: 'haproxy.toml', dest: '/etc/confd/conf.d/haproxy.toml'}
       - { conf: 'haproxy.tmpl', dest: '/etc/confd/templates/haproxy.tmpl'}
      loop_control:
        label: "{{ item.dest }}"

    - name: confd | prepare haproxy.tmpl template file (replace "bind" for stats)
      lineinfile:
        path: /etc/confd/templates/haproxy.tmpl
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
        backrefs: yes
      loop:
       - { regexp: '^.*bind.*:7000$', line: '    bind {{ hostvars[inventory_hostname].inventory_hostname }}:7000' }
       - { regexp: '^.*bind.*:5000$', line: '    bind {{ cluster_vip }}:5000' }
       - { regexp: '^.*bind.*:5001$', line: '    bind {{ cluster_vip }}:5001' }
       - { regexp: '^.*bind.*:5002$', line: '    bind {{ cluster_vip }}:5002' }
       - { regexp: '^.*bind.*:5003$', line: '    bind {{ cluster_vip }}:5003' }
      loop_control:
        label: "{{ item.line }}"
      when: cluster_vip is defined and cluster_vip | length > 0

    - name: confd | prepare haproxy.tmpl template file (replace "bind" for stats)
      lineinfile:
        path: /etc/confd/templates/haproxy.tmpl
        regexp: '{{ item.regexp }}'
        line: '{{ item.line }}'
        backrefs: yes
      loop:
       - { regexp: '^.*bind.*:7000$', line: '    bind {{ hostvars[inventory_hostname].inventory_hostname }}:7000' }
       - { regexp: '^.*bind.*:5000$', line: '    bind {{ hostvars[inventory_hostname].inventory_hostname }}:5000' }
       - { regexp: '^.*bind.*:5001$', line: '    bind {{ hostvars[inventory_hostname].inventory_hostname }}:5001' }
       - { regexp: '^.*bind.*:5002$', line: '    bind {{ hostvars[inventory_hostname].inventory_hostname }}:5002' }
       - { regexp: '^.*bind.*:5003$', line: '    bind {{ hostvars[inventory_hostname].inventory_hostname }}:5003' }
      loop_control:
        label: "{{ item.line }}"
      when: cluster_vip is not defined or cluster_vip | length < 1
  when: add_balancer is defined and add_balancer|bool
  tags: [ confd_conf, confd ]

- name: confd | copy systemd service file
  template:
    src: templates/confd.service.j2
    dest: /etc/systemd/system/confd.service
  tags: [ confd_service, confd ]

- name: confd | restart systemd service
  systemd:
    daemon_reload: yes
    name: confd
    enabled: yes
    state: restarted
  tags: [ confd_restart, confd ]
